version: '3.3'

services:
    od-yolo-api:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
            - '5000:5000'
        image: od-yolo-api
        container_name: od-api-yolov5